version: "3"
services:
  app-nextcloud:
    image: registry.supera.com.br/template-nextcloud:16.0.4
    container_name: app-nextcloud
    ports:
    - "8000:80"
    restart: unless-stopped
  mysql-app:
    image: mariadb
    container_name: mysql-app
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: nextcloud
      MYSQL_ROOT_PASSWORD: nextcloud@123
    restart: unless-stopped
